### PR TITLE
Morse decoder with Elixir

### PR DESCRIPTION
**Pull request by matiasbeckerle**
Probably not the best approach, but it works. I did a hack which I will try to improve some day. Added the whole project so anyone can [install Elixir](https://elixir-lang.org/install.html) and run the project easily. Anyways, the important files:

- `lib/morse.ex`.
- `test/morse_test.exs`

Here is the sausage: https://github.com/MakingSense/coding-dojo/pull/3/files#diff-034ed42181ecd30c24e51db7f0c06898R18

The hack explanation:

I wanted to solve the whole thing using the pipe operator `|>`. The problem I had was that after splitting by words I also need to split by letters. But at some point there is a return that it was sending me the words and not the letters. This is of course the lack of knowledge over the language (this is my first attempt to code something in this language). The hacks consists on translate the words separator (triple space) as another morse symbol.

### CODE REVIEW

**Comment by andresmoschini** [comment]
Hi @matiasbeckerle, I did not have time to review this yet (and neither fix [mine one](https://github.com/MakingSense/coding-dojo/pull/5)), but I think that you should merge it, it will be a shame if you close it without merge.

**Comment by matiasbeckerle** [comment]
Thank you @AlphaGit @andresmoschini. I will wait for @DanielAltamirano's blessing before moving forward.

**Comment by andresmoschini** [comment]
We need your bless @mbeckerle, do not wait for him. ;)

**Comment by mbeckerle** [comment]
Note: @andresmoschini - mbeckerle (me) is not same as @matiasbeckerle. You wanted to comment for him.

**Comment by andresmoschini** [comment]
Ooops, sorry Mike, and thanks for your nice and polite message to make me know about my error.

**Comment by matiasbeckerle** [comment]
Ok based on @andresmoschini and @AlphaGit comments I will merge this one. We can revert it if needed.

**Pull request merged**
